spring.datasource.url=jdbc:postgresql://localhost:5432/ai_project_recommender
server.port = 8081
spring.datasource.username=postgres
spring.datasource.password=saisravani
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect