server.port=${PORT:8081}

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_project_recommender
spring.datasource.username=postgres
spring.datasource.password=saisravani

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
jwt.secret=VGhpc0lzQVNlY3JldEtlckZvckFpUHJvamVjdFJlY29tbWVuZGVyMjAyNlZlcnlMb25nS2V5
jwt.expiration=86400000